version: '3'

services:
  freeswitch:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SIGNALWIRE_TOKEN=${SIGNALWIRE_TOKEN}
    env_file:
      - .env
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5080:5080/tcp"
      - "8021:8021/tcp"
    volumes:
      - ./freeswitch-src/conf:/usr/local/freeswitch/conf
    restart: unless-stopped
    user: root
    command: ./bin/freeswitch 
